skip_commits:
  files:
    - "**/*.md"
    - "**/*.png"
    - "**/*LICENCE"

image: Visual Studio 2022

install:
- ps: |
      [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
      Install-Module Pester -Force
- pwsh: |
      [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
      Install-Module Pester -Force

build: off

test_script:
- ps: |
      Import-Module -Name "Pester" -Force
      Import-Module -Name "C:\projects\windowsosservicing"
      $ResultsPS = Invoke-Pester -OutputFormat NUnitXml -OutputFile $testResultsFile -Show All -PassThru
      $testResultsFile = ".\TestsResults_PS.xml"
      $ResultsPS = Invoke-Pester -Show All -Verbose -PassThru | Tee-Object -FilePath $testResultsFile
      (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))
      If ($ResultsPS.FailedCount -gt 0) {
          throw "$($res.FailedCount) tests failed."
      }
- pwsh: |
      Import-Module -Name "Pester" -Force
      Import-Module -Name "C:\projects\windowsosservicing"
      $testResultsFile = ".\TestsResults_PWSH.xml"
      $ResultsPS = Invoke-Pester -OutputFormat NUnitXml -OutputFile $testResultsFile -Show All -PassThru
      (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))
      If ($ResultsPWSH.FailedCount -gt 0) {
          throw "$($res.FailedCount) tests failed."
      }
